/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for scanning a project directory */
export interface ScanOptions {
  /** Root directory to scan */
  projectDir: string
  /** Path to float.db */
  dbPath: string
  /** Additional patterns to exclude (optional) */
  excludePatterns?: Array<string>
}
/** Warning from scan (non-fatal issues) */
export interface ScanWarning {
  path: string
  message: string
  code: string
}
/** Statistics from the scan */
export interface ScanStats {
  /** Total folders in DB after scan */
  folders: number
  /** Total files in DB after scan */
  files: number
  /** Files stat'd during walk */
  filesWalked: number
  /** Files actually hashed (mtime changed) */
  filesHashed: number
  /** Files skipped (mtime unchanged, used cache) */
  filesSkipped: number
  /** Total scan time in milliseconds */
  durationMs: number
}
/** Result of scanning a project */
export interface ScanResult {
  /** Paths with different hashes */
  changed: Array<string>
  /** New paths not in DB */
  added: Array<string>
  /** Paths in DB but not on disk */
  removed: Array<string>
  /** Scan statistics */
  stats: ScanStats
  /** New root hash */
  rootHash: string
  /** Previous root hash (empty string if first scan) */
  previousRootHash: string
  /** True if root hash matches (no changes at all) */
  unchanged: boolean
  /** Non-fatal warnings */
  warnings: Array<ScanWarning>
}
/** Main scan function - called from Node.js */
export declare function scan(options: ScanOptions): ScanResult
