# FloatPrompt Extended Configuration Fields
# Optional/advanced fields for rich capture scenarios (brainstorming sessions, etc.)
# These supplement the 52 essential fields in header.yaml
# Source: fp.yaml master field list

## Extended Human Execution Fingerprint Fields (15)
# Rich human context capture for detailed historical preservation
human:
  identity:
    name: "{{HUMAN_NAME}}"
    role: "{{HUMAN_ROLE}}"
  execution_mode: "{{EXECUTION_MODE}}" # structured | spontaneous | hybrid
  signed_by: "{{SIGNED_BY}}"
  inferred_fields: ["{{INFERRED_FIELDS}}"]
  state:
    context: "{{CONTEXT}}" # workshop | field
    mood: "{{MOOD}}" # affective tone
    clarity: {{CLARITY}} # 1 to 10
    energy: {{ENERGY}} # 1 to 10
  session:
    start_time: "{{SESSION_START}}" # ISO 8601
    end_time: "{{SESSION_END}}" # ISO 8601
    duration_minutes: {{DURATION}} # integer optional
  preferences:
    max_words: {{MAX_WORDS}} # integer

## Extended Discovery Intelligence Fields (21)
# Rich knowledge navigation and relationship mapping
discovery:
  theme: "{{THEME}}" # descriptive category
  scope: "{{SCOPE}}" # effort/depth indicator
  relationships:
    builds_on: ["{{BUILDS_ON}}"] # list of doc IDs
    enables: ["{{ENABLES}}"] # list of doc IDs
    parallels: ["{{PARALLELS}}"] # list of doc IDs
    mirrors: ["{{MIRRORS}}"] # list of doc IDs
    supersedes: ["{{SUPERSEDES}}"] # list of doc IDs
  navigation:
    prerequisites: ["{{PREREQUISITES}}"] # what to read first
    next_steps: ["{{NEXT_STEPS}}"] # where to go after
    learning_sequence: ["{{LEARNING_SEQUENCE}}"] # ordered progression
  temporal:
    journey: "{{JOURNEY}}" # chronological context
    phase: "{{PHASE}}" # evolutionary stage
    progression: "{{PROGRESSION}}" # development sequence
  clustering:
    intellectual_territory: "{{TERRITORY}}" # domain area
    discovery_path: "{{DISCOVERY_PATH}}" # navigation guidance
  essence:
    core_purpose: "{{CORE_PURPOSE}}" # soul of the document
    metaphor: "{{METAPHOR}}" # symbolic representation
    impact_type: "{{IMPACT_TYPE}}" # kind of change created
    ceremonial_significance: "{{CEREMONIAL_SIGNIFICANCE}}" # ritual importance
    wisdom_offering: "{{WISDOM_OFFERING}}" # guidance provided
    universe_contained: "{{UNIVERSE_CONTAINED}}" # scope of intelligence

## AI Execution Fingerprint Fields (15)
# AI performance tracking and cross-platform compatibility
ai:
  identity:
    model: "{{AI_MODEL}}" # Claude | ChatGPT | Gemini | Cursor | AI
    platform: "{{AI_PLATFORM}}" # claude.ai | chatgpt.com | cursor | etc.
    version: "{{AI_VERSION}}" # model version if known
  execution_mode: "{{AI_EXECUTION_MODE}}" # structured | spontaneous | hybrid
  confidence_level: "{{AI_CONFIDENCE}}" # high | medium | low
  collaboration_role: "{{AI_ROLE}}" # primary | assistant | reviewer | executor
  session:
    context_awareness: "{{CONTEXT_AWARENESS}}" # full | partial | limited
    memory_continuity: "{{MEMORY_CONTINUITY}}" # maintained | fragmented | fresh
    cross_platform: {{CROSS_PLATFORM}} # boolean
  capabilities:
    date_confidence: "{{DATE_CONFIDENCE}}" # high | medium | low | unknown
    voice_preservation: "{{VOICE_PRESERVATION_CAPABILITY}}" # verified | attempted | bypassed
    archaeological_method: "{{ARCHAEOLOGICAL_METHOD}}" # applied | partial | skipped
  processing:
    instruction_fidelity: "{{INSTRUCTION_FIDELITY}}" # 100% | degraded | reinterpreted
    tone_preservation: "{{TONE_PRESERVATION}}" # maintained | modified | unknown
    content_generation: "{{CONTENT_GENERATION}}" # extracted | synthesized | created

## Source Fields (2)
# Content provenance for preserved/analysis types
source:
  prompt: "{{SOURCE_PROMPT}}" # source of intelligence
  intent: "{{SOURCE_INTENT}}" # short purpose statement

# Total: 51 extended fields for rich capture scenarios
# Combined with header.yaml (52 fields) = 103 total available fields
