/**
 * llms.txt Generator
 *
 * Creates the llms.txt index file following the llms.txt specification.
 * https://llmstxt.org/
 */

import type { PageInfo } from '../types.js';

export interface LlmsTxtOptions {
  /** Site title */
  siteTitle?: string;
  /** Site description */
  siteDescription?: string;
  /** Base URL */
  baseUrl?: string;
}

/**
 * Generate llms.txt content
 *
 * Format follows the llms.txt spec:
 * - Title as H1
 * - Description as blockquote
 * - Sections grouping related pages
 * - Links to markdown files
 */
export function generateLlmsTxt(
  pages: PageInfo[],
  options: LlmsTxtOptions = {}
): string {
  const { siteTitle = 'Website', siteDescription, baseUrl = '' } = options;

  const lines: string[] = [];

  // Title
  lines.push(`# ${siteTitle}`);
  lines.push('');

  // Description
  if (siteDescription) {
    lines.push(`> ${siteDescription}`);
    lines.push('');
  }

  // Group pages by directory
  const groups = groupPagesByDirectory(pages);

  // Output each group
  for (const [groupName, groupPages] of Object.entries(groups)) {
    if (groupPages.length === 0) continue;

    lines.push(`## ${formatGroupName(groupName)}`);

    for (const page of groupPages) {
      const mdPath = urlToMarkdownPath(page.url);
      const description = page.description
        ? `: ${truncate(page.description, 80)}`
        : '';
      lines.push(`- [${page.title}](${mdPath})${description}`);
    }

    lines.push('');
  }

  // Add link to full content
  lines.push('## Full Content');
  lines.push(
    `Complete markdown: [/llms-full.txt](${baseUrl}/llms-full.txt)`
  );
  lines.push('');

  // Footer
  lines.push('---');
  lines.push('Generated by FloatPrompt');
  lines.push('');

  return lines.join('\n');
}

/**
 * Group pages by their top-level directory
 */
function groupPagesByDirectory(
  pages: PageInfo[]
): Record<string, PageInfo[]> {
  const groups: Record<string, PageInfo[]> = {
    Pages: [],
  };

  for (const page of pages) {
    const parts = page.url.split('/').filter(Boolean);

    if (parts.length === 0 || parts.length === 1) {
      // Root level pages
      groups['Pages'].push(page);
    } else {
      // Nested pages - group by first directory
      const groupKey = parts[0];
      const groupName = formatGroupName(groupKey);

      if (!groups[groupName]) {
        groups[groupName] = [];
      }
      groups[groupName].push(page);
    }
  }

  // Sort groups: Pages first, then alphabetically
  const sortedGroups: Record<string, PageInfo[]> = {};

  // Pages first (if not empty)
  if (groups['Pages'].length > 0) {
    sortedGroups['Pages'] = groups['Pages'];
  }

  // Rest alphabetically
  const otherKeys = Object.keys(groups)
    .filter((k) => k !== 'Pages')
    .sort();

  for (const key of otherKeys) {
    if (groups[key].length > 0) {
      sortedGroups[key] = groups[key];
    }
  }

  return sortedGroups;
}

/**
 * Format a directory name as a section title
 */
function formatGroupName(name: string): string {
  // Capitalize first letter of each word
  return name
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Convert URL path to markdown file path
 *
 * Examples:
 *   / -> /index.md
 *   /about -> /about.md
 *   /docs/ -> /docs/index.md
 */
function urlToMarkdownPath(url: string): string {
  if (url === '/') {
    return '/index.md';
  }

  if (url.endsWith('/')) {
    return url + 'index.md';
  }

  return url + '.md';
}

/**
 * Truncate text with ellipsis
 */
function truncate(text: string, maxLength: number): string {
  if (text.length <= maxLength) {
    return text;
  }
  return text.slice(0, maxLength - 3) + '...';
}
