/**
 * llms-full.txt Generator
 *
 * Creates a single file containing all markdown content from the site.
 * Allows agents to load complete site context in one request.
 */

import type { PageInfo } from '../types.js';

export interface LlmsFullTxtOptions {
  /** Site title */
  siteTitle?: string;
  /** Site description */
  siteDescription?: string;
  /** Include frontmatter from individual pages */
  includeFrontmatter?: boolean;
}

/**
 * Generate llms-full.txt content
 *
 * Concatenates all page markdown with separators.
 */
export function generateLlmsFullTxt(
  pages: PageInfo[],
  options: LlmsFullTxtOptions = {}
): string {
  const {
    siteTitle = 'Website',
    siteDescription,
    includeFrontmatter = false,
  } = options;

  const lines: string[] = [];

  // Header
  lines.push(`# ${siteTitle} — Complete Content`);
  lines.push('');

  if (siteDescription) {
    lines.push(`> ${siteDescription}`);
    lines.push('');
  }

  lines.push(`Total pages: ${pages.length}`);
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Table of contents
  lines.push('## Table of Contents');
  lines.push('');

  for (const page of pages) {
    const anchor = urlToAnchor(page.url);
    lines.push(`- [${page.title}](#${anchor})`);
  }

  lines.push('');
  lines.push('---');
  lines.push('');

  // Each page's content
  for (let i = 0; i < pages.length; i++) {
    const page = pages[i];
    const anchor = urlToAnchor(page.url);

    // Page header with anchor
    lines.push(`<a id="${anchor}"></a>`);
    lines.push('');

    // Get content without frontmatter (unless requested)
    let content = page.markdown;
    if (!includeFrontmatter) {
      content = stripFrontmatter(content);
    }

    // Add URL reference
    lines.push(`**URL:** ${page.url}`);
    lines.push('');

    // Add content
    lines.push(content.trim());
    lines.push('');

    // Separator (except for last page)
    if (i < pages.length - 1) {
      lines.push('---');
      lines.push('');
    }
  }

  // Footer
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Generated by FloatPrompt*');
  lines.push('');

  return lines.join('\n');
}

/**
 * Convert URL to anchor-safe string
 */
function urlToAnchor(url: string): string {
  return url
    .replace(/^\//, '')          // Remove leading slash
    .replace(/\/$/, '')          // Remove trailing slash
    .replace(/\//g, '-')         // Replace slashes with dashes
    .replace(/[^a-z0-9-]/gi, '') // Remove special chars
    .toLowerCase() || 'home';
}

/**
 * Strip YAML frontmatter from markdown
 */
function stripFrontmatter(markdown: string): string {
  const frontmatterPattern = /^---\n[\s\S]*?\n---\n/;
  return markdown.replace(frontmatterPattern, '');
}
