import { z } from "zod";

/**
 * FloatDoc Schema
 * Format: YAML frontmatter + markdown
 * Use: Context files, maps, navigation — lightweight AI terrain awareness
 *
 * Design principles:
 * 1. Easily generated — half auto-injected by build system
 * 2. Just enough context — one-liners, not paragraphs
 * 3. Terrain awareness — AI reads frontmatter across files, builds mental map
 * 4. Deep dive signal — enough info to know WHEN to read fully
 */

export const FloatDocSchema = z.object({
  // Terrain awareness (human-written or AI-assisted)
  title: z.string(),                     // what is this
  type: z.string(),                      // what kind (nav, context, decisions, spec, guide...)
  status: z.string(),                    // is it current (current, draft, archived, living...)
  description: z.string(),               // one-line content summary — the key routing signal

  // Attribution (auto-generated by build system)
  created: z.string(),                   // YYYY-MM-DD, from git or timestamp
  human_author: z.string(),              // from global config
  ai_model: z.string(),                  // from session/runtime
  ai_updated: z.string(),                // from build time

  // Optional depth (add when needed)
  human_context: z.string().optional(),  // additional human context
  ai_notes: z.string().optional(),       // AI observations
  related: z.string().optional(),        // comma-separated paths for integrity checking
});

// Type exports
export type FloatDoc = z.infer<typeof FloatDocSchema>;
